---
name: app CD

on:
  push:
    branches: ["main"]

jobs:

  create-deployment-files:
    name: create deployment files
    runs-on: ubuntu-latest
    steps:
      - name: plan deployment
        uses: appleboy/ssh-action@master
        with:
          host: 18.195.161.82 
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            cd ~/fullstack-nest-next && sudo bash deploy-app.sh
