---
name: app CD

on:
  push:
    branches: ["main"]

jobs:

  changed-directories:
    name: check changed directories
    runs-on: ubuntu-latest
    outputs:
      deploy-app: ${{steps.app-changed.outputs.all_changed_files_count != '0' && 'deploy_backend' || ''}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check if the app changed
        id: app-changed
        uses: tj-actions/changed-files@v42

  create-deployment-files:
    name: create deployment files
    runs-on: ubuntu-latest
    needs: changed-directories
    steps:
      - name: plan deployment
        uses: appleboy/ssh-action@master
        with:
          host: 3.71.91.3 #fake
          username: ${{ secrets.APP_SSH_USERNAME }} #fake
          password: ${{ secrets.APP_SSH_PASSWORD }} #fake
          port: 22
          script: |
            touch /var/www/html/app/$ docker compose -f docker-compose.prod.yml up -d