---
name: app CD

on:
  push:
    branches: ["main"]

jobs:

  create-deployment-files:
    name: create deployment files
    runs-on: ubuntu-latest
    needs: changed-directories
    steps:
      - name: plan deployment
        uses: appleboy/ssh-action@master
        with:
          host: 3.79.27.4 
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            bash deploy-stack.sh 